name: simple_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  saf: ^1.0.4
  permission_handler: ^12.0.1
  hive_ce: ^2.3.3
  hive_ce_flutter: ^2.3.3
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator:
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
